---
title: Home
pagetitle: "{{< meta title >}} | {{< var title-fix >}}"
include-in-header: 
    - text: |
        <style>.quarto-title > h1.title {display: none !important;}</style>

---

## Introduction

Welcome to AP Computer Science Principles at Berkeley High School, taught by Ms. O'Keefe and Mr. Chang. 

In this course, we'll be studying the big ideas of computing using the [Snap<em>!</em> programming language](https://snap.berkeley.edu/). No matter what career you choose to pursue, an understanding of computer science is becoming increasingly essential in today’s world.

We want you to have fun and learn. This course will be run as a **"lab centric" class** built on project-based learning. You will learn by writing lots of code, not by listening to me talk. There will sometimes be brief lectures near the beginning of class, but mostly your teacher will be helping you and you’ll be helping each other do the work. Working with other people is a key part of your educational experience.  *You will do most of your work paired with another person for support, and you should expect much of your learning will come from figuring out your mistakes/bugs, both on your own and together with your classmates.*

## Outline of Course Objectives and Topics

The AP Computer Science Principles class is a two-semester course which will prepare you for the AP Computer Science Principles Exam. This is the website that you will be mainly be using for classwork all semester long. We'll be using a curriculum adapted from the [Beauty and Joy of Computing (BJC)](http://bjc.edc.org/) which was created from an existing course of the same name at Cal, CS 10.

Units 1-5 cover all of the AP CSP curriculum framework. You will be ready for the exam after completing these key units.

Units 6-8 focus on the abstraction hierarchy of how computers work as well as recursion, a beautiful and powerful CS idea that goes beyond the AP CSP Framework and exam. These units are perfect to enjoy after the exam.

Here are some course objectives that we will cover over the first five units:

- Experience the beauty and the joy of programming
- Understand the nature of programming as problem solving and persevering 
- Understand the basic principles of programming 
- Learn to code fluently in Snap! in a well-structured fashion with effective documentation and code clarity 
- Implement algorithms using conditional and iterative control structures as well as recursion
- Read and discuss the Blown to Bits book and current topics in computer science/technology
- Prepare for the AP CSP exam in the Spring (exam optional)

## Course Resources

This website will be the main source of assignments and instructional material. [Google Classroom](https://classroom.google.com/) will be used for any other communication, notes, and materials. Students will complete most of their work on a computer in the classroom and submit it electronically via Google Classroom.

## Internet Usage

The use of the Internet in class is a ***PRIVILEGE***, this privilege can be revoked or suspended at any time deemed necessary as described in the [BUSD Acceptable Use Policy for Electronic Resources & the Internet](https://www.berkeleyschools.net/wp-content/uploads/2011/12/AUP_Student_form.pdf) which all students and parents/guardians have signed. All students have access to the Internet, unless otherwise specified by a parent/guardian. In addition, the Internet is to be used for educational purposes only as described in the policy.

## Computer Lab Expectations

### Entering the Lab

- Students may have no food or drink of any kind in the lab during class (including candy and gum, but excluding bottled water).  Students working or studying DURING LUNCH may bring their lunch to eat at the tables in the middle.
- Be seated and working when the bell rings.

### Working in the Lab

- There will be no horseplay or offensive language in the lab.
- If you and your partner have a question, ask your neighbors. If they don’t know, then put your name on the help doc and continue to try to figure it out while you wait. This class is primarily about problem solving and students are expected to be putting in effort to solve their own problems at all times. 
- All students have a responsibility to help each other
- All students should treat each other with respect.
- Conversations in the lab should be primarily related to the study of computers.
- Installation and downloading of programs is forbidden without express teacher approval.
- When using the Internet, be sure that you are on appropriate sites. See INTERNET USAGE WARNING above.
- Cell phones, music players, and video games are never to be used in the computer lab and should be turned off or put away and silenced. If I see your phone, I will take it for the rest of the period. If this happens repeatedly I will turn it into the OCI at the end of the period and you will have to retrieve it from there. 
- Handle computer equipment with care.

### Exiting the Lab

- Leave the room as clean or cleaner than when you entered it.
- Save all work and log off of the computer.
- Push chairs under the tables.

**Remember:** the use of the computer lab is for *educational purposes only*. If a student is using the computers during class time for something not related to the assigned work, disciplinary measures will be taken and your parents or guardians will be contacted.

## Grading

Your grade will be split into:

60% Participation and Habit of Work
: This will be measured by checkpoints/response forms, meeting behavior expectations (staying on task, not causing distractions, keeping phone out of sight), and attendance (see below).

5% Computing in the News
: This will be measured by contribution to the weekly "Computing in The News," which will require one presentation per semester, and responses to all presentations given by classmates.

25% Projects
: This will be measured by performance on projects. Students are expected to meet specific requirements listed on the project specficifications and associated rubric.
: In the second semester, this will also include both the practice Create Task and the actual Create Task, which is required of all students regardless of whether or not they plan to take the AP exam.

10% Assessments
: This will be measured by performance on assessments (which are given mainly at the end of each unit) and other quiz/testing tasks (such as AP test related preparation)

### Letter Grade

- 90% and above is an **A**
- 80% and above is a **B**
- 70% and above is a **C**
- 60% and above is a **D**
- under 60% is an **F**


## Attendance

Being in class and on-time is essential to learning. Often, important instructions and material will be presented at the start of class and it is 100% the student’s responsibility to be present to receive this information. If absent, it is the student’s responsibility to make up any missed projects or curriculum. Students should check their Google Classroom for assignments each day. Most assignments are project oriented and as such continue across a span of a few to many days. Students are responsible for any assignments missed while absent, unless otherwise agreed upon.