---
title: "Page 1: What is AI?"
subtitle: "Unit 3, Lab 4, Page 1"
order: 1
---

::: todo
BH to review
<a href="https://docs.google.com/presentation/d/1QZMyeC0wa6xJ1KIFrQXgzCzO4qKKmb68clNM_nvHFPs/edit#slide=id.g33244856d9_0_10" target="_blank">Ken
Kahn's work</a> for TIF a. --MF, 10/16/18
:::

::: learn
**On this page,** you will do online research on image
recognition.
:::

::: vocabFullWidth
**Artificial intelligence (AI)** is a field of computer
science loosely defined as "trying to get computers to think."
:::

This definition has led to a lot of arguments about whether a
computer can ever <em>really</em> think, so John McCarthy, one of the
founders of AI, defined AI as "getting computers to do things that, when
done by human beings, are said to involve intelligence." This definition
allows AI researchers to do their work instead of spending time arguing
about what "thinking" means.

Interestingly, tasks that human beings generally consider to be hard
to do (like playing chess) have turned out to be easier for computers
than tasks people think of as being so easy that we do them "without
thinking," like walking. Another example is seeing, that is, recognizing
images, which is a big field of research in AI.

::: {#first .forYouToDo}
<ol>

<li>

Do your own research to learn more about the current state of AI

::: endnote


Here are some suggested areas where AI is being used to research. Pick one that's interesting to you and learn about it.


<ul>

<li>AI used in chatbots</li>

<li>AI used in image generation</li>

<li>AI used in scientific research</li>

<li>AI used in robotics</li>

<li>AI used in art</li>

<li>AI used in law enforcement</li>

</ul>


:::

</li>

<li>

***One of the biggest growing areas of AI is image and facial recognition.***

Discuss some of the social implications of teaching computers to
understand images. For example, some technologies include positive
implications such as helping people with visual disabilities by
providing AI-generated descriptions of images. And other applications 
can invade people's privacy and are susceptible to bias. 

<ol>

<li>List three possible good consequences of computer face
recognition.</li>

<li>List three possible bad consequences of computer face
recognition.</li>

<li>Brainstorm suggestions for ways to encourage the good consequences
while discouraging the bad ones.</li>

</ol>

</li>

</ol>
:::

::: takeItFurther
<ol type="A">

<li>

In your research, you probably came across terms like **machine
learning** or **neural networks** or **deep
learning**. Research these ways of thinking about artificial
intelligence by searching for articles and videos like these:

<ul>

<li>Video:
<a href="https://scratch.mit.edu/discuss/youtube/bHvf7Tagt18" target="_blank" title="Deep Neural Networks Explained (YouTube)">Machine
Learning & Deep Neural Networks Explained (YouTube)</a></li>

<li><a href="http://www.forbes.com/sites/kevinmurnane/2016/04/01/what-is-deep-learning-and-how-is-it-useful/#40cd3d5810f0" target="_blank" title="What is Deep Learning and How Is It Useful? (Forbes)">What
is Deep Learning and How Is It Useful? (Forbes)</a></li>

</ul>

</li>

<li>

The history of artificial intelligence goes back further than you might
realize. The ideas of robots and artificial intelligence existed before
the 1950s, but the field become more established in the 1950s and 1960s.
Research some early contributions to AI to see both how far we've come
and also how some early challenges still exist today.

<ul>

<li><a href="http://www.computerhistory.org/timeline/ai-robotics/" target="_blank" title="Timeline of Computer History">Timeline
of Computer History</a></li>

<li>Article with videos:
<a href="http://watson.latech.edu/book/intelligence/intelligenceOverview4.html" target="_blank" title="A brief history of artificial intelligence">A
brief history of artificial intelligence</a></li>

</ul>

</li>

</ol>
:::
