---
title: "Page 1: Communication and Community"
subtitle: "Unit 4, Lab 3, Page 1"
order: 1
---

::: todo
<p>pink box new. --MF, 12/21/17</p>

<p>BH: I'm inclined to flush the TIF (make a video) or at least move it
to after the next FYTD.</p>

<p>MF: could use review/light revision; tough to have 2.17 SI labs back
to back</p>
:::

::: learn
<p><strong>In this lab,</strong> you will consider the impacts of
technology on how we build community.</p>

<p><strong>On this page,</strong> you will consider how technology is
used to communicate and how it can impact community.</p>
:::

::: todo
<ul>

<li>GH Feedback 9/14/15: Could we have an example of a completed
citation?
<a href="http://teachingprivacy.org/" >http://teachingprivacy.org/</a>
as used in this reference?</li>

<li>GH Feedback 9/14/15: Breaking up the two greens (For You To Do loses
continuity? The task seems mixed up with the Check it out and the Take
it Further in the middle. The Take It further references the items in
the For You To Do and it a weak link when implementing?</li>

</ul>
:::

::: {#first .forYouToDo}
<ol>

<li>What are some different ways we use technology to communicate?
Generate a list.</li>

::: sidenote
Remember to cite your sources.
:::

<li>Choose one means of communication (such as cell phone call, SMS,
Facebook, Skype, Twitter, etc.) and use the Internet to figure out what
you can about how that technology works.</li>

<li>Identify one way to communicate over the Internet that didn't exist
three years ago.</li>

<li>Identify a <em>social problem</em> that has been solved using
Internet communication, somewhere <em>other than</em> the United States.
<!--(You may find the articles by NYU Prof. <a href="http://shirky.com/writings/" title="Clay Shirky" target="_blank">Clay Shirky</a> helpful.)--></li>

<li>For small group discussion: What are the good and bad points about
having the BJC lessons online, compared with a paper textbook?</li>

</ol>
:::

::: endnote
Check out
<a href="http://www.teachingprivacy.org/" target="_blank" title="Teaching Privacy">Teaching
Privacy</a>, a site about protecting yourself from giving away private
information through social media.
:::

::: takeItFurther
<ol type="A">

<li>Make a short video explaining what you learned about how one of
these ways of communicating works.</li>

</ol>
:::

::: forYouToDo
<ol start="6">

<li>

Four Corners (class activity). Do you "strongly agree," "agree,"
"disagree," or "strongly disagree" with each of the following
statements?

<ul>

<li>Computers are isolating. (That is, they cause us to spend less time
with other people.)</li>

<li>Computers are democratizing. (That is, they give more political
power to ordinary people.)</li>

</ul>

You will choose a viewpoint, then present your reasons for taking that
view.

</li>

</ol>
:::
