---
title: "Component C: Personalized Project Reference"
pagetitle: "{{< meta title >}} | {{< var title-fix >}}"
author: "Ms. O'Keefe and Mr. Chang"
order: 200
---

::: learn

To assist in responding to the written response prompts on exam day, submit required portions of your code by capturing and pasting program code segments you developed during the administration of this task. Screen captures should not be blurry, and text should be at least 10-point font size. Your code segments should not include any comments. These code segments will be made available to you on exam day only if this component is submitted as final in the AP Digital Portfolio by the deadline.

:::

::: takeNote

This reference is to be created independently (NO collaboration). Classmates and/or your teacher can help you troubleshoot any technical problems or guide you in taking screenshots.

You will paste a total of 4 screenshots of your code.

:::

## Procedure

Capture and paste two program code segments you developed during the administration of this task that contain a student-developed procedure that implements an algorithm used in your program and a call to that procedure. 

1. The first program code segment must be a student-developed
procedure that:
    - Defines the procedure’s name and return type (if necessary)
    - Contains and uses one or more parameters that have an effect on
    the functionality of the procedure
    - Implements an algorithm that includes sequencing, selection, and
    iteration

2. The second program code segment must show where your student-developed procedure is being called in your program.

## List

Capture and paste two program code segments you developed during the administration of this task that contain a list (or other collection type) being used to manage complexity in your program.

1. The first program code segment must show how data have been stored in the list.
2. The second program code segment must show the data in the same list being used, such as creating new data from the existing data or accessing multiple elements in the list, as part of fulfilling the program’s purpose
