---
title: "AP Performance Create Task"
pagetitle: "{{< meta title >}} | {{< var title-fix >}}"
---

::: learn
For this course, you will be working on a project that will be graded both by your teacher and the AP exam scorers.

The project is mainly graded based off your understanding of the main ideas of the course (ergo "Computer Science Principles"), not how amazing your project is. 

This task consists of 30% of the total AP exam score.
:::

::: takeNote

Keep in mind that on the actual Create Task, I (or any other teacher) are not allowed to answer anything specific about your project (“Do I have this in my project?”, “Can you help me code this?”, etc. are questions that we cannot answer).

:::

The project consists of these main scored components:

1. **Program**
2. **Video**
3. **Personalized Project Reference**
    - The (1) Program, (2) Video, and (3) Personal Project Reference are things that you do outside of the exam time, i.e. in-class or at home and consists of a third of the project score (2 points out of 6 points). 
4. **Written Response**
    - The Written Response is something that you do during the exam using the (2) Personal Project Reference and consists of two thirds of the project score (4 points out of 6 points).
