---
title: "Page 1: Why Use Simulations?"
subtitle: "Unit 5, Lab 2, Page 1"
order: 1
---

::: learn
**In this lab,** you will explore how simulations can be
used to gain insight into real-world phenomena.

**On this page,** you will learn why simulations are
used instead of real-world experiments.
:::

::: vocabFullWidth
::: ap-standard
AAP-3.F.1, AAP-3.F.2
:::

**Simulations** are computer representations of real
things or situations that vary over time. A simulation is an abstraction
designed for a particular purpose.
:::

::: ap-standard
AAP-3.F.3, AAP-3.F.6
:::



There are many reasons to use computer simulations rather than
real-world experiments to prove things about a situation. Experimenting
in the real world may be:

<ul>

<li>**Expensive**, such as testing a proposed new airplane
that might fall apart in strong winds. A simulation of the airplane and
wind can eliminate some bad designs before building and testing a real
airplane.</li>

<li>**Time-consuming**, such as testing the effects of a
genetic mutation in a species across generations.</li>

<li>**Dangerous**, such as testing whether a nuclear
reactor will survive an earthquake.</li>

<li>**Unethical**, such as giving a population a disease to
test how fast it spreads.</li>

</ul>



::: ap-standard
AAP-3.F.4
:::

Computer simulations rarely capture the full complexity of real
situations. For example, simulations of global climate change should
account for hundreds of interconnected factors such as wind patterns,
the course of rivers, geological fault lines that cause earthquakes, and
interactions of local plants and animals. However, because of
limitations in computer speed, researchers leave out details to make
simulations practical.

::: ap-standard
AAP-3.F.5
:::

There are risks in making simplifications. For example, there might
be an interaction between elements of the real situation that isn't
obvious but turns out to be crucial. A simplification might lose the
details that would have shown that interaction. Another issue is that if
you have ideas in mind about what's going on, you are more likely to
emphasize details---even unconsciously---that support your ideas. (This
kind of distortion is so common that researchers have a name for it:
<em>confirmation bias</em>.)

::: {#first .forYouToDo}
<ol>

<li>Come up with some examples of complex real-life phenomena for which
it would be impractical, impossible, dangerous, or unethical to conduct
real-world experiments.</li>

::: ap-standard
AAP-3.F part a, AAP-3.F part b
:::

<li>Explain how simulations may help with our understanding of these
phenomena. What are some pros and cons of using computers to explore
these situations?</li>

</ol>
:::
